// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SadaqaAccounting.Database.DatabaseContexts;

#nullable disable

namespace SadaqaAccounting.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.AssetManagement.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<string>("AssetNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("StatusId");

                    b.ToTable("Assets", "AssetManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.CashBankManagement.Cash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.ToTable("Cashes", "Cash&BankManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("StatusId");

                    b.ToTable("Banks", "Cash&BankManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.BankLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("BankId");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("BankLedgers", "Cash&BankManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.CashLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CashId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("CashId");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("CashLedgers", "Cash&BankManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.OpeningBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("CashId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentModeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("BankId");

                    b.HasIndex("CashId");

                    b.HasIndex("PaymentModeId");

                    b.ToTable("OpeningBalances", "Cash&BankManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.DonorManagement.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("StatusId");

                    b.ToTable("Donors", "DonorManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.ExpenseManagement.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("CashId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentModeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("BankId");

                    b.HasIndex("CashId");

                    b.HasIndex("EventId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("PaymentModeId");

                    b.ToTable("Expenses", "ExpenseManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.ExpenseManagement.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.ToTable("ExpenseCategories", "ExpenseManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.IncomeManagement.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("CashId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("IncomeCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MonthId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentModeId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptBookNo")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("BankId");

                    b.HasIndex("CashId");

                    b.HasIndex("DonorId");

                    b.HasIndex("EventId");

                    b.HasIndex("IncomeCategoryId");

                    b.HasIndex("MonthId");

                    b.HasIndex("PaymentModeId");

                    b.ToTable("Incomes", "IncomeManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.IncomeManagement.IncomeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDonorBased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.ToTable("IncomeCategories", "IncomeManagement");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Actions", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.FeatureActionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureActionMappings", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Roles", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.RoleActionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleActionMappings", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.UserAccessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccessMappings", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AccountUnits", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Companies", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StatusId");

                    b.ToTable("Employees", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EnumTypes", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("EnumTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EnumTypeId");

                    b.ToTable("EnumTypeCollections");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.ToTable("Events", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedTableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Features", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Modules", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.ReportAccessControl.ReportRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ReportCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReportGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("StatusId");

                    b.ToTable("ReportRegistries", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.ReportAccessControl.ReportUserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReportRegistryId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReportRegistryId");

                    b.HasIndex("UserId");

                    b.ToTable("ReportUserAccess", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.UserAccountUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountUnitId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccountUnits", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.UserLoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserLoginHistories", "MasterSettings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("ApplicationUserTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("ForcePasswordChanged")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("ApplicationUserTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.AssetManagement.Asset", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("Assets")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.CashBankManagement.Cash", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("Cashes")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.Bank", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("Banks")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("Banks")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.BankLedger", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("BankLedgers")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.Cash_BankManagement.Bank", "Bank")
                        .WithMany("BankLedgers")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Bank");

                    b.Navigation("SourceType");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.CashLedger", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("CashLedgers")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.CashBankManagement.Cash", "Cash")
                        .WithMany("CashLedgers")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Cash");

                    b.Navigation("SourceType");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.OpeningBalance", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.Cash_BankManagement.Bank", "Bank")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.CashBankManagement.Cash", "Cash")
                        .WithMany("OpeningBalances")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "PaymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Bank");

                    b.Navigation("Cash");

                    b.Navigation("PaymentMode");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.DonorManagement.Donor", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("Donors")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.ExpenseManagement.Expense", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("Expenses")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.Cash_BankManagement.Bank", "Bank")
                        .WithMany("Expenses")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.CashBankManagement.Cash", "Cash")
                        .WithMany("Expenses")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Event", "Event")
                        .WithMany("Expenses")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.ExpenseManagement.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "PaymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Bank");

                    b.Navigation("Cash");

                    b.Navigation("Event");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("PaymentMode");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.ExpenseManagement.ExpenseCategory", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.IncomeManagement.Income", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("Incomes")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.Cash_BankManagement.Bank", "Bank")
                        .WithMany("Incomes")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.CashBankManagement.Cash", "Cash")
                        .WithMany("Incomes")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.DonorManagement.Donor", "Donor")
                        .WithMany("Incomes")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Event", "Event")
                        .WithMany("Incomes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.IncomeManagement.IncomeCategory", "IncomeCategory")
                        .WithMany("Incomes")
                        .HasForeignKey("IncomeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Month")
                        .WithMany("IncomeMonths")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "PaymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("Bank");

                    b.Navigation("Cash");

                    b.Navigation("Donor");

                    b.Navigation("Event");

                    b.Navigation("IncomeCategory");

                    b.Navigation("Month");

                    b.Navigation("PaymentMode");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.IncomeManagement.IncomeCategory", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("IncomeCategories")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Action", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("Actions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.FeatureActionMapping", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Action", "Action")
                        .WithMany("FeatureActionMappings")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Feature", "Feature")
                        .WithMany("FeatureActionMappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Role", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("Roles")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.RoleActionMapping", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Action", "Action")
                        .WithMany("RoleActionMappings")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Feature", "Feature")
                        .WithMany("RoleActionMappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Role", "Role")
                        .WithMany("RoleActionMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.UserAccessMapping", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Action", "Action")
                        .WithMany("UserAccessMappings")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Feature", "Feature")
                        .WithMany("UserAccessMappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.User", "User")
                        .WithMany("UserAccessMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Feature");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Company", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("Companies")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Employee", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("Employees")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumType", "EnumType")
                        .WithMany("EnumTypeCollections")
                        .HasForeignKey("EnumTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnumType");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Event", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("Events")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Feature", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Module", "Module")
                        .WithMany("Features")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("Features")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Module", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("Modules")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.ReportAccessControl.ReportRegistry", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Module", "Module")
                        .WithMany("ReportRegistries")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "Status")
                        .WithMany("ReportRegistries")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.ReportAccessControl.ReportUserAccess", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.ReportAccessControl.ReportRegistry", "ReportRegistry")
                        .WithMany("ReportUserAccesses")
                        .HasForeignKey("ReportRegistryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.User", "User")
                        .WithMany("ReportUserAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportRegistry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.UserAccountUnit", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", "AccountUnit")
                        .WithMany("UserAccountUnits")
                        .HasForeignKey("AccountUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.User", "User")
                        .WithMany("UserAccountUnits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.User", b =>
                {
                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", "ApplicationUserType")
                        .WithMany()
                        .HasForeignKey("ApplicationUserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SadaqaAccounting.Model.Models.MasterSettings.Employee", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUserType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.CashBankManagement.Cash", b =>
                {
                    b.Navigation("CashLedgers");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("OpeningBalances");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.Cash_BankManagement.Bank", b =>
                {
                    b.Navigation("BankLedgers");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("OpeningBalances");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.DonorManagement.Donor", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.ExpenseManagement.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.IncomeManagement.IncomeCategory", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Action", b =>
                {
                    b.Navigation("FeatureActionMappings");

                    b.Navigation("RoleActionMappings");

                    b.Navigation("UserAccessMappings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccessControl.Role", b =>
                {
                    b.Navigation("RoleActionMappings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.AccountUnit", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("BankLedgers");

                    b.Navigation("Banks");

                    b.Navigation("CashLedgers");

                    b.Navigation("Cashes");

                    b.Navigation("Donors");

                    b.Navigation("Events");

                    b.Navigation("ExpenseCategories");

                    b.Navigation("Expenses");

                    b.Navigation("IncomeCategories");

                    b.Navigation("Incomes");

                    b.Navigation("OpeningBalances");

                    b.Navigation("UserAccountUnits");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Employee", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumType", b =>
                {
                    b.Navigation("EnumTypeCollections");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Enum.EnumTypeCollection", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Banks");

                    b.Navigation("Companies");

                    b.Navigation("Employees");

                    b.Navigation("Features");

                    b.Navigation("IncomeMonths");

                    b.Navigation("Modules");

                    b.Navigation("ReportRegistries");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Event", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Feature", b =>
                {
                    b.Navigation("FeatureActionMappings");

                    b.Navigation("RoleActionMappings");

                    b.Navigation("UserAccessMappings");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.Module", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("ReportRegistries");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.ReportAccessControl.ReportRegistry", b =>
                {
                    b.Navigation("ReportUserAccesses");
                });

            modelBuilder.Entity("SadaqaAccounting.Model.Models.MasterSettings.User", b =>
                {
                    b.Navigation("ReportUserAccesses");

                    b.Navigation("UserAccessMappings");

                    b.Navigation("UserAccountUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
